### ISSUE TITLE
Initial deployment roadmap

### ISSUE THREAD

**Issue by SteveRyan-ASU** [asuengineering/pitchfork-people#1]
## Acceptance Criteria

- [x] Create CPT and associated taxonomy for Pitchfork People. (slug: pfpeople)
- [x] Prevent CPT from generating any page templates at all. Also prevent info from being discoverable via API if possible.
- [x] Create sync mechanism between entry in CPT and JSON feed from ASU Search.
- [x] Ensure sync'd data can be overridden or preserved in DB if person is no longer with ASU. Set ability to sync or preserve with a toggle in the admin.
- [x] Create acf/profile-data block for inclusion of one profile within the block editor.
- [x] Create (name) block to pull whole directory listing from Search based on pre-built search group. Layout should be driven by app-webdir-ui components exclusively.
- [ ] Create cron event that runs daily(?) to update contents of CPT with search updates.

**Comment by SteveRyan-ASU** [comment]
Closing this issue as completed or no longer on the roadmap (in the case of the last bullet point above.)
